# (DON'T CHANGE) remote base path and project repo folder name
base_path = "/home/smr"
repo_name = "summerset"

# (SET PROPERLY) for each group, its DNS domain names
[reg]
host0 = "smr@c220g5-120128.wisc.cloudlab.us"
host1 = "smr@c220g5-110510.wisc.cloudlab.us"
host2 = "smr@c220g5-120125.wisc.cloudlab.us"
host3 = "smr@c220g5-120130.wisc.cloudlab.us"
host4 = "smr@c220g5-120115.wisc.cloudlab.us"
host5 = "smr@c220g5-110517.wisc.cloudlab.us"

[wan]
host0 = "smr@c220g5-110918.wisc.cloudlab.us"
host1 = "smr@hp163.utah.cloudlab.us"
host2 = "smr@clnode122.clemson.cloudlab.us"
host3 = "smr@pc100.cloudlab.umass.edu"
host4 = "smr@apt068.apt.emulab.net"
host5 = "smr@c220g5-110917.wisc.cloudlab.us"
host6 = "smr@hp180.utah.cloudlab.us"
host7 = "smr@clnode130.clemson.cloudlab.us"
host8 = "smr@pc70.cloudlab.umass.edu"
host9 = "smr@apt069.apt.emulab.net"
