# (DON'T CHANGE) remote base path and project repo folder name
base_path = "/home/smr"
repo_name = "summerset"

# (SET PROPERLY) for each group, its DNS domain names
[reg]
host0 = "josehu@c220g5-120128.wisc.cloudlab.us"
host1 = "josehu@c220g5-110510.wisc.cloudlab.us"
host2 = "josehu@c220g5-120125.wisc.cloudlab.us"
host3 = "josehu@c220g5-120130.wisc.cloudlab.us"
host4 = "josehu@c220g5-120115.wisc.cloudlab.us"
host5 = "josehu@c220g5-110517.wisc.cloudlab.us"

[wan]
node0 = "josehu@c220g5-110918.wisc.cloudlab.us"
node1 = "josehu@hp163.utah.cloudlab.us"
node2 = "josehu@clnode122.clemson.cloudlab.us"
node3 = "josehu@pc100.cloudlab.umass.edu"
node4 = "josehu@apt068.apt.emulab.net"
node5 = "josehu@c220g5-110917.wisc.cloudlab.us"
node6 = "josehu@hp180.utah.cloudlab.us"
node7 = "josehu@clnode130.clemson.cloudlab.us"
node8 = "josehu@pc70.cloudlab.umass.edu"
node9 = "josehu@apt069.apt.emulab.net"
